"""crear tablas usuario expediente obra borrador

Revision ID: 4ba2b7c3069c
Revises:
Create Date: 2026-07-20 00:31:57.918063

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ba2b7c3069c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usuario",
        sa.Column(
            "id",
            sa.BigInteger(),
            server_default=sa.text("GENERATED ALWAYS AS IDENTITY"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("usuario", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("rol", sa.String(), nullable=False),
        sa.Column("cargo", sa.String(), nullable=False),
        sa.Column("activo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rol IN ('administrador', 'supervisor', 'operador_juridico')", name="usuario_rol_check"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usuario_usuario"), "usuario", ["usuario"], unique=True)
    op.create_table(
        "expediente",
        sa.Column(
            "id",
            sa.BigInteger(),
            server_default=sa.text("GENERATED ALWAYS AS IDENTITY"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("numero_caso", sa.String(), nullable=False),
        sa.Column("tipo_proceso", sa.String(), nullable=False),
        sa.Column("estado", sa.String(), server_default=sa.text("'activo'"), nullable=False),
        sa.Column("tribunal_origen", sa.String(), nullable=False),
        sa.Column("procesado_nombre", sa.String(), nullable=False),
        sa.Column("delito", sa.String(), nullable=False),
        sa.Column("abierto_por", sa.BigInteger(), nullable=False),
        sa.Column("procesado_grado", sa.String(), nullable=True),
        sa.Column("sentencia_origen", sa.String(), nullable=True),
        sa.Column("fojas_total", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.CheckConstraint("estado IN ('activo', 'archivado')", name="expediente_estado_check"),
        sa.CheckConstraint(
            "tipo_proceso IN ('consulta', 'apelacion_incidental')",
            name="expediente_tipo_proceso_check",
        ),
        sa.ForeignKeyConstraint(
            ["abierto_por"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("expediente_created_at_idx", "expediente", ["created_at"], unique=False)
    op.create_index("expediente_estado_idx", "expediente", ["estado"], unique=False)
    op.create_index(op.f("ix_expediente_abierto_por"), "expediente", ["abierto_por"], unique=False)
    op.create_index(op.f("ix_expediente_numero_caso"), "expediente", ["numero_caso"], unique=True)
    op.create_table(
        "borrador",
        sa.Column(
            "id",
            sa.BigInteger(),
            server_default=sa.text("GENERATED ALWAYS AS IDENTITY"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("expediente_id", sa.BigInteger(), nullable=False),
        sa.Column("propietario_id", sa.BigInteger(), nullable=False),
        sa.Column("tipo", sa.String(), nullable=False),
        sa.Column("estado", sa.String(), server_default=sa.text("'borrador'"), nullable=False),
        sa.Column("contenido", sa.String(), nullable=False),
        sa.Column("plantilla_usada", sa.String(), nullable=True),
        sa.Column("contexto_recuperado", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("estado IN ('borrador', 'publicado')", name="borrador_estado_check"),
        sa.CheckConstraint(
            "tipo IN ('dictamen_radicatoria', 'proyecto_auto_vista_consulta', 'proyecto_auto_vista_apelacion', 'sugerencia_argumentacion')",
            name="borrador_tipo_check",
        ),
        sa.ForeignKeyConstraint(["expediente_id"], ["expediente.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["propietario_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "borrador_expediente_propietario_idx",
        "borrador",
        ["expediente_id", "propietario_id"],
        unique=False,
    )
    op.create_index(
        "borrador_publicados_idx",
        "borrador",
        ["expediente_id"],
        unique=False,
        postgresql_where=sa.text("estado = 'publicado'"),
    )
    op.create_index(op.f("ix_borrador_expediente_id"), "borrador", ["expediente_id"], unique=False)
    op.create_index(
        op.f("ix_borrador_propietario_id"), "borrador", ["propietario_id"], unique=False
    )
    op.create_table(
        "obra",
        sa.Column(
            "id",
            sa.BigInteger(),
            server_default=sa.text("GENERATED ALWAYS AS IDENTITY"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("expediente_id", sa.BigInteger(), nullable=False),
        sa.Column("propietario_id", sa.BigInteger(), nullable=False),
        sa.Column("tipo_documento", sa.String(), nullable=False),
        sa.Column("nombre_archivo", sa.String(), nullable=False),
        sa.Column("contenido_texto", sa.String(), nullable=False),
        sa.Column(
            "estado_visibilidad", sa.String(), server_default=sa.text("'privado'"), nullable=False
        ),
        sa.Column("fuente", sa.String(), server_default=sa.text("'carga_usuario'"), nullable=False),
        sa.Column("ruta_archivo", sa.String(), nullable=True),
        sa.Column("fojas_inicio", sa.Integer(), nullable=True),
        sa.Column("fojas_fin", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "estado_visibilidad IN ('privado', 'publicado')", name="obra_estado_visibilidad_check"
        ),
        sa.CheckConstraint(
            "fuente IN ('carga_usuario', 'generado_sistema')", name="obra_fuente_check"
        ),
        sa.CheckConstraint(
            "tipo_documento IN ('sentencia', 'memorial_apelacion', 'auto_interlocutorio', 'oficio_elevacion', 'acta_audiencia', 'requerimiento_fiscal', 'dictamen_radicatoria', 'dictamen_fondo', 'relacion_obrados', 'proyecto_auto_vista', 'auto_vista', 'doctrina', 'otro')",
            name="obra_tipo_documento_check",
        ),
        sa.ForeignKeyConstraint(["expediente_id"], ["expediente.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["propietario_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_obra_expediente_id"), "obra", ["expediente_id"], unique=False)
    op.create_index(op.f("ix_obra_propietario_id"), "obra", ["propietario_id"], unique=False)
    op.create_index(
        "obra_expediente_propietario_idx", "obra", ["expediente_id", "propietario_id"], unique=False
    )
    op.create_index(
        "obra_publicadas_idx",
        "obra",
        ["expediente_id"],
        unique=False,
        postgresql_where=sa.text("estado_visibilidad = 'publicado'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "obra_publicadas_idx",
        table_name="obra",
        postgresql_where=sa.text("estado_visibilidad = 'publicado'"),
    )
    op.drop_index("obra_expediente_propietario_idx", table_name="obra")
    op.drop_index(op.f("ix_obra_propietario_id"), table_name="obra")
    op.drop_index(op.f("ix_obra_expediente_id"), table_name="obra")
    op.drop_table("obra")
    op.drop_index(op.f("ix_borrador_propietario_id"), table_name="borrador")
    op.drop_index(op.f("ix_borrador_expediente_id"), table_name="borrador")
    op.drop_index(
        "borrador_publicados_idx",
        table_name="borrador",
        postgresql_where=sa.text("estado = 'publicado'"),
    )
    op.drop_index("borrador_expediente_propietario_idx", table_name="borrador")
    op.drop_table("borrador")
    op.drop_index(op.f("ix_expediente_numero_caso"), table_name="expediente")
    op.drop_index(op.f("ix_expediente_abierto_por"), table_name="expediente")
    op.drop_index("expediente_estado_idx", table_name="expediente")
    op.drop_index("expediente_created_at_idx", table_name="expediente")
    op.drop_table("expediente")
    op.drop_index(op.f("ix_usuario_usuario"), table_name="usuario")
    op.drop_table("usuario")
    # ### end Alembic commands ###
