"""add reranker_endpoint_id to configuracion_rag

Revision ID: 4ffdd6dca550
Revises: 9b3c5e1f8a01
Create Date: 2026-08-11 18:50:18.249845

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ffdd6dca550"
down_revision: str | Sequence[str] | None = "9b3c5e1f8a01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "configuracion_rag", sa.Column("reranker_endpoint_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("configuracion_rag", "reranker_endpoint_id")
    # ### end Alembic commands ###
