"""add cargo check, obra fields, chat tables, trigger updated_at

Revision ID: 8f345a460a82
Revises: 4ba2b7c3069c
Create Date: 2026-07-20 05:01:23.456789

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f345a460a82"
down_revision: str | Sequence[str] | None = "4ba2b7c3069c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Trigger function genérica para updated_at
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER LANGUAGE plpgsql AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$;
    """)

    # 2. CHECK constraint usuario.cargo (valores institucionales TSJM)
    op.create_check_constraint(
        "usuario_cargo_check",
        "usuario",
        "cargo IN ('Fiscal', 'Vocal', 'Presidente', 'Secretaria', 'Vocal S.A.C.', 'Presidente de Sala', 'Otro')",
    )

    # 3. Add columns to obra FIRST (needed for check constraint)
    op.add_column("obra", sa.Column("tamano_archivo", sa.BigInteger(), nullable=True))
    op.add_column(
        "obra",
        sa.Column(
            "estado_procesamiento",
            sa.String(),
            server_default=sa.text("'completado'"),
            nullable=False,
        ),
    )

    # 4. CHECK constraint obra.estado_procesamiento (after column exists)
    op.create_check_constraint(
        "obra_estado_procesamiento_check",
        "obra",
        "estado_procesamiento IN ('pendiente', 'procesando', 'completado', 'fallido')",
    )

    # 5. New tables
    op.create_table(
        "espacio_trabajo",
        sa.Column(
            "id",
            sa.BigInteger(),
            server_default=sa.text("GENERATED ALWAYS AS IDENTITY"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("expediente_id", sa.BigInteger(), nullable=False),
        sa.Column("propietario_id", sa.BigInteger(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("tipo", sa.String(), server_default=sa.text("'personalizado'"), nullable=False),
        sa.Column("estado", sa.String(), server_default=sa.text("'activo'"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "length(trim(both from nombre)) > 0", name="espacio_trabajo_valid_nombre"
        ),
        sa.CheckConstraint(
            "tipo IN ('fijado', 'archivado', 'personalizado')", name="espacio_trabajo_tipo_check"
        ),
        sa.CheckConstraint(
            "estado IN ('activo', 'eliminado')", name="espacio_trabajo_estado_check"
        ),
        sa.ForeignKeyConstraint(["expediente_id"], ["expediente.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["propietario_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("espacio_trabajo_estado_idx", "espacio_trabajo", ["estado"], unique=False)
    op.create_index(
        "espacio_trabajo_expediente_propietario_idx",
        "espacio_trabajo",
        ["expediente_id", "propietario_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_espacio_trabajo_expediente_id"), "espacio_trabajo", ["expediente_id"], unique=False
    )
    op.create_index(
        op.f("ix_espacio_trabajo_propietario_id"),
        "espacio_trabajo",
        ["propietario_id"],
        unique=False,
    )

    op.create_table(
        "chat_privado",
        sa.Column(
            "id",
            sa.BigInteger(),
            server_default=sa.text("GENERATED ALWAYS AS IDENTITY"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("expediente_id", sa.BigInteger(), nullable=False),
        sa.Column("espacio_trabajo_id", sa.BigInteger(), nullable=True),
        sa.Column("propietario_id", sa.BigInteger(), nullable=False),
        sa.Column("titulo", sa.String(), nullable=False),
        sa.Column("estado", sa.String(), server_default=sa.text("'activo'"), nullable=False),
        sa.Column("prioridad", sa.String(), server_default=sa.text("'media'"), nullable=False),
        sa.Column("contexto_legal", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ultimo_mensaje_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "contexto_legal IN ('caso_legal', 'audiencia', 'reunion', 'antecedente', 'documento_legal', 'consulta_general')",
            name="chat_privado_contexto_legal_check",
        ),
        sa.CheckConstraint("length(trim(both from titulo)) > 0", name="chat_privado_valid_titulo"),
        sa.CheckConstraint(
            "estado IN ('activo', 'archivado', 'eliminado')", name="chat_privado_estado_check"
        ),
        sa.CheckConstraint(
            "prioridad IN ('baja', 'media', 'alta', 'critica')", name="chat_privado_prioridad_check"
        ),
        sa.ForeignKeyConstraint(["expediente_id"], ["expediente.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["espacio_trabajo_id"], ["espacio_trabajo.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["propietario_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("chat_privado_estado_idx", "chat_privado", ["estado"], unique=False)
    op.create_index(
        "chat_privado_expediente_propietario_idx",
        "chat_privado",
        ["expediente_id", "propietario_id"],
        unique=False,
    )
    op.create_index(
        "chat_privado_ultimo_mensaje_at_idx", "chat_privado", ["ultimo_mensaje_at"], unique=False
    )
    op.create_index(
        op.f("ix_chat_privado_expediente_id"), "chat_privado", ["expediente_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_privado_espacio_trabajo_id"),
        "chat_privado",
        ["espacio_trabajo_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_privado_propietario_id"), "chat_privado", ["propietario_id"], unique=False
    )

    op.create_table(
        "mensaje_chat",
        sa.Column(
            "id",
            sa.BigInteger(),
            server_default=sa.text("GENERATED ALWAYS AS IDENTITY"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("usuario_id", sa.BigInteger(), nullable=False),
        sa.Column("tipo", sa.String(), nullable=False),
        sa.Column("razonamiento", sa.String(), server_default=sa.text("''"), nullable=False),
        sa.Column("contenido", sa.String(), nullable=False),
        sa.Column("estado", sa.String(), server_default=sa.text("'activo'"), nullable=False),
        sa.Column("posicion", sa.Integer(), nullable=False),
        sa.Column("metadatos", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "estado IN ('activo', 'editado', 'eliminado')", name="mensaje_chat_estado_check"
        ),
        sa.CheckConstraint(
            "length(trim(both from contenido)) > 0", name="mensaje_chat_valid_contenido"
        ),
        sa.CheckConstraint("tipo IN ('user', 'bot')", name="mensaje_chat_tipo_check"),
        sa.ForeignKeyConstraint(["chat_id"], ["chat_privado.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "mensaje_chat_chat_posicion_idx", "mensaje_chat", ["chat_id", "posicion"], unique=False
    )
    op.create_index("mensaje_chat_estado_idx", "mensaje_chat", ["estado"], unique=False)
    op.create_index(op.f("ix_mensaje_chat_chat_id"), "mensaje_chat", ["chat_id"], unique=False)
    op.create_index(
        op.f("ix_mensaje_chat_usuario_id"), "mensaje_chat", ["usuario_id"], unique=False
    )

    op.create_table(
        "documento_chat",
        sa.Column(
            "id",
            sa.BigInteger(),
            server_default=sa.text("GENERATED ALWAYS AS IDENTITY"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("mensaje_id", sa.BigInteger(), nullable=False),
        sa.Column("usuario_id", sa.BigInteger(), nullable=False),
        sa.Column("nombre_original", sa.String(), nullable=False),
        sa.Column("tamano_archivo", sa.BigInteger(), nullable=False),
        sa.Column("tipo_documento", sa.String(), nullable=False),
        sa.Column(
            "estado_procesamiento",
            sa.String(),
            server_default=sa.text("'pendiente'"),
            nullable=False,
        ),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "estado_procesamiento IN ('pendiente', 'procesando', 'completado', 'fallido')",
            name="documento_chat_estado_procesamiento_check",
        ),
        sa.CheckConstraint(
            "length(trim(both from nombre_original)) > 0", name="documento_chat_valid_nombre"
        ),
        sa.CheckConstraint("tamano_archivo > 0", name="documento_chat_valid_tamano"),
        sa.CheckConstraint(
            "tipo_documento IN ('pdf', 'doc', 'docx', 'txt', 'md', 'csv', 'json', 'png', 'jpg', 'jpeg', 'bmp', 'gif', 'webp', 'tiff')",
            name="documento_chat_tipo_documento_check",
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chat_privado.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["mensaje_id"], ["mensaje_chat.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documento_chat_chat_id"), "documento_chat", ["chat_id"], unique=False)
    op.create_index(
        op.f("ix_documento_chat_mensaje_id"), "documento_chat", ["mensaje_id"], unique=False
    )
    op.create_index(
        op.f("ix_documento_chat_usuario_id"), "documento_chat", ["usuario_id"], unique=False
    )

    # 6. Trigger updated_at en tablas EXISTENTES con columna updated_at
    for table in ("borrador",):
        op.execute(
            f"CREATE TRIGGER update_{table}_updated_at "
            f"BEFORE UPDATE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()"
        )

    # 7. Trigger updated_at en tablas NUEVAS (después de crearlas)
    for table in ("espacio_trabajo", "chat_privado", "mensaje_chat"):
        op.execute(
            f"CREATE TRIGGER update_{table}_updated_at "
            f"BEFORE UPDATE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Drop triggers updated_at (all)
    for table in ("borrador", "espacio_trabajo", "chat_privado", "mensaje_chat"):
        op.execute(f"DROP TRIGGER IF EXISTS update_{table}_updated_at ON {table}")

    # 2. Drop trigger function
    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column()")

    # 3. Drop CHECK constraints
    op.drop_constraint("usuario_cargo_check", "usuario", type_="check")
    op.drop_constraint("obra_estado_procesamiento_check", "obra", type_="check")

    # 4. Drop new tables (auto-generated)
    op.drop_index(op.f("ix_documento_chat_usuario_id"), table_name="documento_chat")
    op.drop_index(op.f("ix_documento_chat_mensaje_id"), table_name="documento_chat")
    op.drop_index(op.f("ix_documento_chat_chat_id"), table_name="documento_chat")
    op.drop_table("documento_chat")
    op.drop_index("mensaje_chat_estado_idx", table_name="mensaje_chat")
    op.drop_index("mensaje_chat_chat_posicion_idx", table_name="mensaje_chat")
    op.drop_index(op.f("ix_mensaje_chat_usuario_id"), table_name="mensaje_chat")
    op.drop_index(op.f("ix_mensaje_chat_chat_id"), table_name="mensaje_chat")
    op.drop_table("mensaje_chat")
    op.drop_index("chat_privado_ultimo_mensaje_at_idx", table_name="chat_privado")
    op.drop_index("chat_privado_expediente_propietario_idx", table_name="chat_privado")
    op.drop_index("chat_privado_estado_idx", table_name="chat_privado")
    op.drop_index(op.f("ix_chat_privado_propietario_id"), table_name="chat_privado")
    op.drop_index(op.f("ix_chat_privado_espacio_trabajo_id"), table_name="chat_privado")
    op.drop_index(op.f("ix_chat_privado_expediente_id"), table_name="chat_privado")
    op.drop_table("chat_privado")
    op.drop_index("espacio_trabajo_estado_idx", table_name="espacio_trabajo")
    op.drop_index("espacio_trabajo_expediente_propietario_idx", table_name="espacio_trabajo")
    op.drop_index(op.f("ix_espacio_trabajo_propietario_id"), table_name="espacio_trabajo")
    op.drop_index(op.f("ix_espacio_trabajo_expediente_id"), table_name="espacio_trabajo")
    op.drop_table("espacio_trabajo")

    # 5. Drop obra columns
    op.drop_column("obra", "estado_procesamiento")
    op.drop_column("obra", "tamano_archivo")
    # ### end Alembic commands ###
